### ISSUE TITLE
Please name related created resources uniquely

### ISSUE THREAD

**Issue by deathweaselx86** [aws-samples/retail-demo-store#52] opened 2020-07-23 16:39 UTC
Someone at my org deployed this, but didn't tear it down. Late, a different person attempted to deploy this but it failed because `RetailDemoStore-users-TaskRole already exists`. I would expect all of these resources to be named uniquely. Can we make that happen?

**Comment by james-jory** [comment] 2020-07-28 14:27
Thanks, @deathweaselx86. Most resources are uniquely named during deployment but some have fixed names since they are accessed by name in code in the workshop notebooks. Making all resources uniquely named would require the notebooks to resolve these names. We need to find an elegant approach to this that does not add confusing complexity to the notebooks. You're right, though, that we need to figure this out. As for the TaskRole's, we should be able to use dynamic names for those.

**Comment by james-jory** [comment] 2020-08-11 13:35
We will work on this issue in phases where the goal of the first phase will be to support multiple deployments in a single account but just in different regions. Some research and testing needs to be done to verify but this should just involve making sure that IAM resources are uniquely named. This includes IAM roles in the CloudFormation templates and roles created in notebooks (such as the [1.1-Personalize](https://github.com/aws-samples/retail-demo-store/blob/master/workshop/1-Personalization/1.1-Personalize.ipynb) workshop). All other services should be regional or already use dynamic names.

The second phase will tackle using dynamic names throughout the project so that multiple deployments in the same account and same region will be supported.

**Comment by alexchirayath** [comment] 2020-08-28 07:53
Hi
@patrick-239  and @james-jory 
Multi-region deployment is still not available since IAM roles are still being used. 
I just tried it and reveived the following error:

`RetailDemoStore-orders-TaskRole already exists`

**Comment by patrick-239** [comment] 2020-08-28 08:06
How did you launch a stack (via button on GitHub page)?

**Comment by alexchirayath** [comment] 2020-08-28 16:41
@patrick-239 
I am trying to deploy it in the "Deploy for Development" mode but I am staging the resources and template in my own s3 buckets using the stage.sh script. However, I believe this would be an issue in all modes of deployment.
The issue is due to hard coding in resource names like roles as seen [here](https://github.com/aws-samples/retail-demo-store/blob/b7af99e0a46d68775228e8efd4870b759ccc6f4e/aws/cloudformation-templates/services/service/service.yaml#L120) and since IAM roles are account-level resources , any userdeploying in multiple regions could face this error

**Comment by james-jory** [comment] 2020-08-28 18:11
@alexchirayath Are you sure you're using the latest templates? The merged changes no longer name task roles using the format you noted in your error above. They are named with a prefix of the stack name + region. This will ensure that role names are unique across the account for multiple deployments (albeit in separate regions).

**Comment by alexchirayath** [comment] 2020-08-28 18:58
Thanks for the quick follow up. It seems I didnt have all the changes merged it. My apologies. Running the updated branch now, will report back if i see any errors

**Comment by patrick-239** [comment] 2020-08-28 19:16
@alexchirayath soon we will release another update (pull request already created) and it will be possible to deploy several demo in a same region.

**Comment by alexchirayath** [comment] 2020-09-16 17:13
> @alexchirayath soon we will release an another update (pull request already created) and it will be possible to deploy several demos in a same region.

Hi @patrick-239 :
Just following up on this issue. I remember the PR being closed due to some macro name limitations. Are we still on track to support multiple deployments in the same region, same account?

**Comment by james-jory** [comment] 2020-09-18 21:11
@alexchirayath I thought support for deployments in separate regions in the same account would satisfy your requirements. Has that changed?

**Comment by BastLeblanc** [comment] 2024-02-01 20:49
closing as stack supports deployment in multi-region is good enough seperation.

**Closed by BastLeblanc** 2024-02-01 20:49 UTC
